{{- if .Values.publish.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "business-central.fullname" . }}
  labels:
    {{- include "business-central.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "business-central.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "business-central.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: OnFailure
      initContainers:
        - name: download
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.publish.download.image.repository }}:{{ .Values.publish.download.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.publish.download.image.pullPolicy }}
          args: ["-NuGetLocation", "{{ .Values.publish.download.params.nugetLocation }}", "-PatSecretPath", "/secret/pat", "-DependenciesJson", {{ .Values.publish.download.params.dependencies | toJson | quote }}, "-ProjectPath", "/a"]
          volumeMounts:
            - name: nuget-pat
              mountPath: /secret
            - name: temp-download
              mountPath: /a
      containers:
        - name: publish
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.publish.image.repository }}:{{ .Values.publish.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.publish.image.pullPolicy }}
          args: ["-user", "admin", "-password", "{{ .Values.password }}", "-appFile", "/a/.alpackages/", "-devServer", "http://{{ include "business-central.fullname" . }}:7049/BC"]
          volumeMounts:
            - name: temp-download
              mountPath: /a
      volumes:
        - name: nuget-pat
          secret:
            secretName: {{ .Values.publish.download.params.patSecretName }}
        - name: temp-download
          emptyDir: {}
      {{- with .Values.publish.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.publish.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.publish.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}