apiVersion: v1
kind: Service
metadata:
  name: {{ include "business-central.fullname" . }}
  labels:
    {{- include "business-central.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.soap }}
      targetPort: soap
      protocol: TCP
      name: soap
    - port: {{ .Values.service.ports.odata }}
      targetPort: odata
      protocol: TCP
      name: odata
    - port: {{ .Values.service.ports.dev }}
      targetPort: dev
      protocol: TCP
      name: dev
    - port: {{ .Values.service.ports.dl }}
      targetPort: dl
      protocol: TCP
      name: dl
  selector:
    {{- include "business-central.selectorLabels" . | nindent 4 }}
